"""Show error hotspots and finite-scale bending associations without retraining."""
import json
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from analyze_generated_one_error_location import OUT
from make_generated_one_joint_curve_view import ink


def full(v,active):
    a=np.zeros(784);a[active]=v;return a


def figures(r,c,e):
    m=r['models']['clipped'];near=m['within_5_percent_any_physical_face'];inside=m['away_from_all_5_percent_faces']
    fig=plt.figure(figsize=(14.2,9),facecolor='white')
    fig.text(.045,.969,'Errors rise near knob limits; bending has a modest association',fontsize=19,weight='bold',va='top')
    fig.text(.045,.921,'16,384 generated 1s for error maps; 1,024 interior images for local bending probes. The fitted five-dimensional manifold is unchanged.',fontsize=10.5)
    gs=fig.add_gridspec(1,3,left=.07,right=.95,top=.825,bottom=.51,wspace=.38)
    ax=fig.add_subplot(gs[0,0]);bars=[near['rms_image_L2'],inside['rms_image_L2']]
    ax.bar([0,1],bars,color=['#bc6327','#2868a8'],width=.60)
    ax.set_xticks([0,1],['Within 5% of\nany knob limit','Away from\nall 5% limits'],fontsize=10)
    ax.set_ylabel('RMS image L2 error',fontsize=10);ax.set_ylim(0,.215);ax.spines[['top','right']].set_visible(False)
    ax.set_title('Errors after clipping',fontsize=12,pad=12)
    for i,v in enumerate([near,inside]):
        ax.text(i,bars[i]+.008,f"{bars[i]:.3f}\n{v['point_share_percent']:.0f}% of images",ha='center',fontsize=9)
    ax.text(.5,-.31,'41% of images contribute 55% of squared error.',transform=ax.transAxes,ha='center',fontsize=9)
    ax=fig.add_subplot(gs[0,1]);pair=m['knob_pair_bins']['cx_cy']
    im=ax.imshow(np.array(pair['rms_image_L2']).T,origin='lower',extent=[14,15,14,15],vmin=0,vmax=.3,cmap='Blues',aspect='auto')
    ax.set_xlabel('Horizontal center (px)',fontsize=10);ax.set_ylabel('Vertical center (px)',fontsize=10)
    ax.set_title('Centers: averaged over other three knobs',fontsize=11,pad=12)
    cb=fig.colorbar(im,ax=ax,pad=.03,fraction=.045);cb.set_label('RMS image L2 error',fontsize=9)
    ax=fig.add_subplot(gs[0,2]);feature=np.mean(c['0.02_curvature'],axis=1);error=np.linalg.norm(c['clipped']-c['truth'],axis=1)
    ax.scatter(feature,error,s=10,color='#2868a8',alpha=.30,edgecolors='none')
    ax.set_xlabel('Normal bending proxy: larger = more bending',fontsize=9)
    ax.set_ylabel('Clipped image L2 error',fontsize=10);ax.set_ylim(0,.43)
    ax.spines[['top','right']].set_visible(False);ax.set_title('Modest association: rank correlation 0.24',fontsize=11,pad=12)
    for j,color in [(4,'#d57619'),(5,'#8a3c8b')]:
        row=int(np.flatnonzero(c['indices']==e['indices'][j])[0]);ax.scatter(feature[row],error[row],s=48,color=color,edgecolors='black',linewidths=.5)
    ax.text(.5,-.31,'Strongest-bending 10% contribute 11.3% of error.',transform=ax.transAxes,ha='center',fontsize=9)
    bottom=fig.add_gridspec(1,6,left=.045,right=.955,top=.335,bottom=.14,wspace=.22)
    for half,j in enumerate([4,5]):
        t=e['truth'][j];p=e['clipped'][j];label=str(e['labels'][j]);color=['#d57619','#8a3c8b'][half]
        for k,value in enumerate([t,p,t-p]):
            ax=fig.add_subplot(bottom[0,half*3+k])
            title=['Exact generated image','Learned image, clipped','Truth − learned'][k]
            if k<2:ink(ax,full(value,e['active']),title,f'L2 error {np.linalg.norm(t-p):.3f}' if k==1 else '')
            else:
                ax.imshow(full(value,e['active']).reshape(28,28),cmap='RdBu_r',vmin=-.15,vmax=.15,interpolation='nearest')
                ax.set_xticks([]);ax.set_yticks([]);ax.set_title(title,fontsize=10,pad=10)
                ax.text(.5,-.09,f'Max |error| {np.max(abs(t-p)):.3f}',transform=ax.transAxes,ha='center',fontsize=9)
        fig.text(.045+half*.475,.39,label,color=color,fontsize=11,weight='bold')
    fig.text(.045,.075,'Images: 28 × 28 ink coverage, white = 0, black = 1. Error maps: red = missing ink; blue = excess; common scale ±0.15 (larger values saturate).',fontsize=10)
    fig.text(.045,.034,'Bending uses ten paths at 2% range scale: twice the chord displacement outside the local five-direction plane / squared pixel step size.',fontsize=10)
    fig.savefig(OUT/'error_locations.png',dpi=145);plt.close(fig)

    fig,axes=plt.subplots(1,5,figsize=(14.3,4.6),sharey=True);fig.subplots_adjust(left=.055,right=.985,top=.77,bottom=.28,wspace=.18)
    fig.text(.04,.96,'Where error changes across each physical knob range',fontsize=18,weight='bold',va='top')
    fig.text(.04,.87,'16,384 uniformly sampled generated 1s. Each point aggregates over the other four knobs; lines connect bin averages.',fontsize=10.5)
    for i,(ax,name) in enumerate(zip(axes,r['knob_order'])):
        lo,hi=r['ranges'][i];values=lo+(np.arange(10)+.5)*(hi-lo)/10
        for model,color,label in [('raw','#b86325','Raw learned pixels'),('clipped','#2868a8','After clipping')]:
            ax.plot(values,[b['rms_image_L2'] for b in r['models'][model]['knob_bins'][name]],'o-',markersize=3.5,color=color,label=label)
        ax.set_title(name,fontsize=12);ax.set_xlabel('Degrees' if name=='lean' else 'Pixels',fontsize=10)
        ax.set_ylim(.09,.225);ax.spines[['top','right']].set_visible(False);ax.grid(axis='y',alpha=.2)
    axes[0].set_ylabel('RMS image L2 error',fontsize=10);axes[2].legend(loc='upper center',bbox_to_anchor=(.5,-.31),ncol=2,frameon=False,fontsize=10)
    fig.text(.04,.044,'Higher error is not restricted to one setting. Center and height limits show elevation; lean has several bands rather than one sharp-turn hotspot.',fontsize=10.3)
    fig.savefig(OUT/'knob_error_profiles.png',dpi=145);plt.close(fig)


HTML='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Where errors concentrate</title><style>
:root{color-scheme:light dark;--bg:#f4f7fa;--card:#fff;--text:#172a3b;--muted:#546777;--line:#dce4ec;--blue:#2365a8}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.6 system-ui,sans-serif}main{max-width:1160px;margin:auto;padding:30px 24px 70px}h1{font-size:34px;line-height:1.2}h2{font-size:23px;margin-top:0}section{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:24px;margin:24px 0}a{color:var(--blue)}.lead{font-size:21px}.muted{color:var(--muted);font-size:14px}.controls{display:flex;gap:16px;align-items:center;flex-wrap:wrap;margin:18px 0}select,input{font:inherit}select{padding:6px;max-width:100%}.images{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}figure{margin:0;text-align:center}.images canvas{width:100%;max-width:210px;image-rendering:pixelated;border:1px solid var(--line)}figcaption{font-size:14px}table{width:100%;border-collapse:collapse}td,th{padding:9px;text-align:left;border-bottom:1px solid var(--line);font-variant-numeric:tabular-nums}.scroll{overflow:auto}.metric{font-weight:600}.wide{width:100%;height:auto}.plot{display:block;max-width:100%;height:auto;margin:auto;touch-action:manipulation}details{margin:18px 0}@media(prefers-color-scheme:dark){:root{--bg:#101923;--card:#172431;--text:#e8eef5;--muted:#a8bacb;--line:#324455;--blue:#79b6ed}}@media(max-width:720px){main{padding:20px 12px}section{padding:18px}h1{font-size:28px}.images{grid-template-columns:1fr 1fr}table{font-size:12px}}
</style></head><body><main><p><a href="../failures/">← Failure analysis</a> · <a href="../midpoints/">Reference-image averaging</a> · <a href="../">Learned manifold</a></p><h1>Where do the errors concentrate?</h1><p class="lead">Error is spread across the family, with elevated error near knob limits. Local bending predicts it only modestly.</p>
<section><h2>The concentration in numbers</h2><p>These measurements use the same unchanged learned manifold and 16,384 uniform generated images from the earlier failure analysis. Image L2 error is Euclidean distance across all 784 coverage pixels. Error share means share of summed squared error.</p><div class="controls"><label><input id="clip" type="checkbox" checked> Clip learned pixels to [0, 1]</label></div><div class="scroll"><table><thead><tr><th>Group</th><th>Share of images</th><th>Share of squared error</th><th>RMS image error</th></tr></thead><tbody id="concentration"></tbody></table></div><p>Within 5% of a knob limit means at least one knob is in the lowest or highest 5% of its allowed range. That includes 41% of this five-knob cloud. The fitted-chart boundary is different: at least one inferred decoder coordinate reaches its [0, 1] bound. Reaching it is an association, not proof of a projection failure.</p><img class="wide" src="error_locations.png" alt="Boundary error comparison, physical center error map and local bending association with contrasting image examples"></section>
<section><h2>Map error across two knobs</h2><div class="controls"><label>Knob pair <select id="pair"></select></label></div><canvas id="map" class="plot" width="600" height="450"></canvas><p id="mapInfo" class="metric"></p><p class="muted">Each cell averages squared errors across all examples in that pair of physical-knob bins, then takes a square root. The other three knobs vary freely. This is a statistical slice of the five-dimensional family, not its full geometry. Hover or tap a cell for its count and error. Colors share a fixed RMS scale from 0 to 0.30.</p><img class="wide" src="knob_error_profiles.png" alt="Raw and clipped RMS errors in ten bins across each of the five knob ranges"></section>
<section><h2>Is sharper bending where it fails?</h2><p>For 1,024 interior images, take small rendered steps before and after each image along ten paths: each of the five knobs alone and five fixed joint directions. Measure how much the image-change direction turns, and how far the averaged endpoints stray from the true center. The normal bending proxy removes changes lying in the local tangent plane and normalizes by pixel-space step size. This discounts mere changes in speed or motion inside that plane.</p><div class="controls"><label>Step scale <select id="step"><option value="0.005">0.5% of knob range</option><option value="0.02" selected>2% of knob range</option></select></label><label>Local feature <select id="feature"><option value="mean_normal_bending">Mean normal bending</option><option value="max_normal_bending">Largest normal bending</option><option value="max_turn_angle_degrees">Largest turn angle</option><option value="max_midpoint_chord_error">Largest midpoint chord error</option></select></label></div><canvas id="scatter" class="plot" width="600" height="430"></canvas><p id="association" class="metric"></p><p id="overshoot" class="muted"></p><p class="muted">Each dot is one actual generated image. Click a dot to inspect it below. Rank correlation ranges from −1 to +1; larger positive values mean the feature more consistently accompanies larger errors. Bending is a finite-scale proxy over ten paths, not a global curvature tensor. The symmetric probes use interior points at least 2.5% away from every physical knob limit; they do not directly test the extreme boundary cases.</p></section>
<section><h2>Inspect a result</h2><div class="controls"><label>Selected example <select id="example"></select></label></div><p id="exampleInfo" class="metric"></p><div class="images"><figure><canvas id="truth" width="28" height="28"></canvas><figcaption>Exact generated image</figcaption></figure><figure><canvas id="learned" width="28" height="28"></canvas><figcaption>Learned reconstruction</figcaption></figure><figure><canvas id="error" width="28" height="28"></canvas><figcaption>Truth − learned</figcaption></figure></div><p id="imageInfo" class="muted"></p><div class="scroll"><table><thead><tr><th>Knob</th><th>Physical setting</th></tr></thead><tbody id="knobs"></tbody></table></div><p class="muted">Images: white = no ink, black = full ink; magenta flags raw out-of-range values with amplified tint. Signed error: red = missing ink, blue = excess, scale ±0.15; larger values saturate. The small-error strong-bending example and large-error weak-bending example are selected counterexamples, not typical values of their groups.</p></section>
<section><h2>What this says about the failure mode</h2><p>After clipping, the worst 10% of images contribute 35.3% of squared error; the other 90% still contribute 64.7%. Within the interior bending cohort, the strongest-bending 10% contribute 11–12%, close to their share of images. Mean normal bending has rank correlation 0.14 at the smaller step and 0.24 at the larger step. Scalar overshoot has weaker associations, 0.05 and 0.13 respectively.</p><p>The evidence points to a broadly distributed approximation error, elevated near physical limits and some knob bands. Sharper local bending can make interpolation harder, but these probes do not show errors dominated by a few sharp turns. A finite fitted grid, node estimates, smoothing, boundary coverage and coordinate projection remain separate possible contributors.</p><p>The original 14,389 fitting images show the same boundary pattern more weakly: after clipping, near-limit RMS error is 0.094 versus 0.085 away from limits. That covering cloud deliberately includes lattice and near-face samples, so its distribution differs from the uniform diagnostic cloud.</p><p>The renderer can change its pixel-change direction when a stroke edge crosses pixel boundaries. Those changes need not make the visible stroke bend. This is geometry in image space. The learned decoder is deterministic at a fixed coordinate; overshooting is not uncertainty or a time delay while the model catches up.</p><p>In image space, 85.7% of clipped squared error is on partially covered target pixels, and 39.0% lies in three-row bands around the top and bottom caps. Being at a cap near an integer pixel-row boundary does not produce a clear monotonic error increase in this cloud. Where in an image an error occurs is distinct from which region of the five-knob family produces it.</p></section>
<details><summary>Definitions, results and figures</summary><p><a href="README.md">Method and limitations</a> · <a href="results.json">All summary measurements</a> · <a href="curvature_samples.npz">Local bending probes</a> · <a href="image_examples.npz">Selected image examples</a></p></details></main>
<script>const D=__DATA__;
const $=id=>document.getElementById(id);const norm=a=>Math.sqrt(a.reduce((s,v)=>s+v*v,0));const f=x=>x.toFixed(3);let selected=D.examples[0],selectedSample=-1;
function model(){return $('clip').checked?'clipped':'raw';}
function pred(e){return $('clip').checked?e.raw.map(v=>Math.max(0,Math.min(1,v))):e.raw;}
function errorOf(e){const p=pred(e);return norm(e.truth.map((v,k)=>v-p[k]));}
function image(id,a,error=false){const ctx=$(id).getContext('2d'),im=ctx.createImageData(28,28),values=Array(784).fill(0);D.active.forEach((p,k)=>values[p]=a[k]);values.forEach((x,i)=>{let rgb;if(error){const w=Math.min(1,Math.abs(x)/.15);rgb=x>=0?[255,255*(1-w),255*(1-w)]:[255*(1-w),255*(1-w),255];}else{const bounded=Math.max(0,Math.min(1,x)),s=255*(1-bounded);rgb=[s,s,s];if(x<-1e-6||x>1+1e-6){const w=Math.min(1,.1+3*Math.abs(x-bounded));rgb=rgb.map((v,k)=>(1-w)*v+w*[199,38,168][k]);}}rgb.forEach((v,k)=>im.data[4*i+k]=Math.round(v));im.data[4*i+3]=255;});ctx.putImageData(im,0,0);}
function showImage(){const p=pred(selected),error=selected.truth.map((v,k)=>v-p[k]);image('truth',selected.truth);image('learned',p);image('error',error,true);$('exampleInfo').textContent=(selected.label||'Selected curvature-cohort image')+' · index '+selected.index+' · image L2 error '+f(norm(error));$('imageInfo').textContent=selectedSample>=0?'This dot belongs to the interior local-bending cohort.':'This selected example is not one of the 1,024 local-bending probes.';$('knobs').innerHTML=D.names.map((n,k)=>'<tr><td>'+n+'</td><td>'+f(selected.knobs[k])+'</td></tr>').join('');}
function table(){const m=D.results.models[model()];const rows=[['All images',m.overall],['Worst 1%',m.largest_error_fractions['0.01']],['Worst 5%',m.largest_error_fractions['0.05']],['Worst 10%',m.largest_error_fractions['0.1']],['Within 5% of any physical knob limit',m.within_5_percent_any_physical_face],['Away from all 5% physical limits',m.away_from_all_5_percent_faces],['Decoder coordinate reaches chart boundary',m.fitted_chart_boundary]];$('concentration').innerHTML=rows.map(([n,v])=>'<tr><td>'+n+'</td><td>'+v.point_share_percent.toFixed(1)+'%</td><td>'+v.squared_error_share_percent.toFixed(1)+'%</td><td>'+f(v.rms_image_L2)+'</td></tr>').join('');}
function map(){const ctx=$('map').getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,600,450);const p=D.results.models[model()].knob_pair_bins[$('pair').value],a=D.names.indexOf(p.axes[0]),b=D.names.indexOf(p.axes[1]),left=85,top=28,size=300;for(let x=0;x<10;x++)for(let y=0;y<10;y++){const t=Math.min(1,p.rms_image_L2[x][y]/.3);ctx.fillStyle='rgb('+[247*(1-t)+6*t,251*(1-t)+54*t,255*(1-t)+109*t].map(Math.round).join(',')+')';ctx.fillRect(left+x*30,top+(9-y)*30,30,30);}ctx.strokeStyle='#172a3b';ctx.strokeRect(left,top,size,size);ctx.fillStyle='#172a3b';ctx.font='13px system-ui';ctx.textAlign='center';for(let i=0;i<=5;i++){const fx=i/5;ctx.fillText(f(D.ranges[a][0]+fx*(D.ranges[a][1]-D.ranges[a][0])),left+fx*size,top+size+22);ctx.textAlign='right';ctx.fillText(f(D.ranges[b][0]+fx*(D.ranges[b][1]-D.ranges[b][0])),left-9,top+size-fx*size+4);ctx.textAlign='center';}ctx.fillText(p.axes[0]+(a===4?' (degrees)':' (pixels)'),left+size/2,top+size+48);ctx.save();ctx.translate(18,top+size/2);ctx.rotate(-Math.PI/2);ctx.fillText(p.axes[1]+(b===4?' (degrees)':' (pixels)'),0,0);ctx.restore();for(let j=0;j<100;j++){const t=j/99;ctx.fillStyle='rgb('+[247*(1-t)+6*t,251*(1-t)+54*t,255*(1-t)+109*t].map(Math.round).join(',')+')';ctx.fillRect(420,top+(99-j)*3,18,3);}ctx.fillStyle='#172a3b';ctx.textAlign='left';ctx.fillText('0.30',445,top+5);ctx.fillText('0',445,top+size);ctx.fillText('RMS image L2',420,top+size+26);$('mapInfo').textContent='Other three knobs are averaged; every cell contains measured images.';}
function scatter(){const ctx=$('scatter').getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,600,430);const h=$('step').value,feature=$('feature').value;const values=D.samples.map(e=>e.features[h][feature]),errors=D.samples.map(e=>errorOf(e));const maxX=Math.max(...values)*1.05,maxY=.47,left=70,top=25,w=460,height=290;ctx.strokeStyle='#172a3b';ctx.beginPath();ctx.moveTo(left,top);ctx.lineTo(left,top+height);ctx.lineTo(left+w,top+height);ctx.stroke();D.samples.forEach((e,i)=>{ctx.fillStyle=i===selectedSample?'#c46020':'rgba(38,99,164,.35)';ctx.beginPath();ctx.arc(left+values[i]/maxX*w,top+(1-errors[i]/maxY)*height,i===selectedSample?5:2.7,0,Math.PI*2);ctx.fill();});ctx.font='12px system-ui';ctx.fillStyle='#172a3b';ctx.textAlign='center';for(let j=0;j<=4;j++){ctx.fillText(f(maxX*j/4),left+w*j/4,top+height+22);ctx.textAlign='right';ctx.fillText(f(maxY*j/4),left-10,top+height-height*j/4+5);ctx.textAlign='center';}ctx.fillText($('feature').value.replaceAll('_',' ')+' (larger = stronger)',left+w/2,top+height+50);ctx.save();ctx.translate(17,top+height/2);ctx.rotate(-Math.PI/2);ctx.fillText('Image L2 error',0,0);ctx.restore();const a=D.results.curvature.scales[h].feature_associations[feature][model()];$('association').textContent='Rank correlation '+a.spearman_error_correlation.toFixed(3)+' · highest-feature '+a.highest_feature_decile.point_share_percent.toFixed(1)+'% of images contribute '+a.highest_feature_decile.squared_error_share_percent.toFixed(1)+'% of squared error.';const v=D.results.curvature.scales[h].bounds_violation_association;$('overshoot').textContent='Separately, mean normal bending vs scalar overshoot energy has rank correlation '+v.spearman_error_correlation.toFixed(3)+'.';}
function update(){table();map();scatter();showImage();}
function mapEvent(ev){const rect=$('map').getBoundingClientRect(),x=(ev.clientX-rect.left)*600/rect.width,y=(ev.clientY-rect.top)*450/rect.height;if(x<85||x>=385||y<28||y>=328)return;const i=Math.floor((x-85)/30),j=9-Math.floor((y-28)/30),p=D.results.models[model()].knob_pair_bins[$('pair').value];$('mapInfo').textContent=p.axes.join(' × ')+' bin '+(i+1)+', '+(j+1)+' · '+p.counts[i][j]+' images · RMS image L2 '+f(p.rms_image_L2[i][j]);}
$('map').addEventListener('mousemove',mapEvent);$('map').addEventListener('click',mapEvent);
$('scatter').addEventListener('click',ev=>{const rect=$('scatter').getBoundingClientRect(),x=(ev.clientX-rect.left)*600/rect.width,y=(ev.clientY-rect.top)*430/rect.height,h=$('step').value,feature=$('feature').value,values=D.samples.map(e=>e.features[h][feature]),maxX=Math.max(...values)*1.05;let best=-1,dist=Infinity;D.samples.forEach((e,i)=>{const error=errorOf(e);const dx=70+values[i]/maxX*460-x,dy=25+(1-error/.47)*290-y,d=dx*dx+dy*dy;if(d<dist){best=i;dist=d;}});selectedSample=best;selected=D.samples[best];scatter();showImage();});
$('pair').innerHTML=Object.keys(D.results.models.clipped.knob_pair_bins).map(k=>'<option value="'+k+'">'+D.results.models.clipped.knob_pair_bins[k].axes.join(' × ')+'</option>').join('');$('pair').value='cx_cy';$('example').innerHTML=D.examples.map((e,i)=>'<option value="'+i+'">'+e.label+'</option>').join('');$('example').addEventListener('input',()=>{selected=D.examples[Number($('example').value)];selectedSample=D.samples.findIndex(e=>e.index===selected.index);scatter();showImage();});$('clip').addEventListener('input',update);$('pair').addEventListener('input',map);['step','feature'].forEach(id=>$(id).addEventListener('input',scatter));update();
</script></body></html>'''


def main():
    r=json.loads((OUT/'results.json').read_text());c=np.load(OUT/'curvature_samples.npz');e=np.load(OUT/'image_examples.npz')
    figures(r,c,e)
    samples=[]
    for i,index in enumerate(c['indices']):
        features={}
        for h in ['0.005','0.02']:
            features[h]=dict(mean_normal_bending=float(np.mean(c[h+'_curvature'][i])),max_normal_bending=float(np.max(c[h+'_curvature'][i])),
                max_turn_angle_degrees=float(np.max(c[h+'_angle'][i])),max_midpoint_chord_error=float(np.max(c[h+'_bend'][i])))
        samples.append(dict(index=int(index),knobs=c['knobs'][i].tolist(),truth=c['truth'][i].tolist(),raw=c['raw'][i].tolist(),features=features))
    examples=[dict(index=int(index),label=str(e['labels'][j]),knobs=e['knobs'][j].tolist(),truth=e['truth'][j].tolist(),raw=e['raw'][j].tolist()) for j,index in enumerate(e['indices'])]
    data=dict(results=r,names=r['knob_order'],ranges=r['ranges'],active=np.flatnonzero(c['active']).tolist(),samples=samples,examples=examples)
    (OUT/'index.html').write_text(HTML.replace('__DATA__',json.dumps(data,separators=(',',':'))))
    m=r['models']['clipped'];lines=['# Error location and local bending','','The fine fitted grid is unchanged. Full-cloud results use cached pixel-only projections for 16,384 uniform Sobol images, seed 740. No fit, refit, model selection or output correction beyond the explicitly labelled clipping is performed.','',
        'Image L2 is Euclidean pixel distance over all 784 ink-coverage values. RMS image error = sqrt(mean per-image squared error). Concentration percentages sum squared error, not image counts or visible magenta area.','',
        '## Where errors concentrate','','| Group | Share of images | Share of clipped squared error | RMS image L2 |','| --- | ---: | ---: | ---: |']
    for label,key in [('Within 5% of any physical knob limit','within_5_percent_any_physical_face'),('Away from all 5% physical limits','away_from_all_5_percent_faces'),('At a fitted decoder-coordinate boundary','fitted_chart_boundary')]:
        v=m[key];lines.append(f"| {label} | {v['point_share_percent']:.2f}% | {v['squared_error_share_percent']:.2f}% | {v['rms_image_L2']:.5f} |")
    lines+=['','The worst 10% of images contribute 35.25% of clipped squared error, leaving 64.75% across the other 90%. All pairwise knob maps use ten equal physical-range bins per axis and average over the other three knobs. They do not display the entire five-dimensional geometry. Fitted-chart boundary contact is an association, not proof of a failed closest-point search.','',
        'The original 14,389 fitting images show a weaker elevation near limits: clipped RMS 0.09381 near versus 0.08545 away. That cloud includes boundary and lattice oversampling, so it is not the same distribution as the uniform diagnostic cloud.','',
        '## Local bending check','','The same 1,024 images are drawn uniformly without replacement from cloud points at least 2.5% away from every physical knob limit, seed 1008. The cohort therefore excludes extreme boundary points. Five single-knob paths and five fixed random joint paths use unit directions in normalized setting space. Symmetric probe scales are 0.005 and 0.02, with all endpoints within the legal box.','',
        'Before-to-center and center-to-after pixel vectors define a turn angle. Half their second image difference is the midpoint chord displacement. A local tangent span comes from central finite differences at 0.001 range fraction and a rank-filtered SVD (relative singular cutoff 1e-6). Projecting the chord displacement off this span removes tangent acceleration. The normal bending proxy is twice the normal displacement magnitude divided by the squared mean endpoint-to-center image distance. Ten-path averages and maxima are proxies at a finite scale, not a global curvature tensor.','',
        '| Probe scale | Mean normal bending vs clipped error rank correlation | Highest-bending decile error share | Mean normal bending vs scalar overshoot rank correlation |','| ---: | ---: | ---: | ---: |']
    for h,s in r['curvature']['scales'].items():
        v=s['feature_associations']['mean_normal_bending']['clipped'];o=s['bounds_violation_association']
        lines.append(f"| {h} | {v['spearman_error_correlation']:.4f} | {v['highest_feature_decile']['squared_error_share_percent']:.2f}% | {o['spearman_error_correlation']:.4f} |")
    lines+=['','Scalar overshoot energy is sum squared distance of raw learned pixels to [0,1]. It differs from reconstruction error and from error reduction after clipping.','',
        'Results show elevated error near physical knob limits and only modest interior curvature associations. No causal share is attributed to finite grid resolution, node approximation, regularization, sampling density or projection. The worst boundary cases are not directly tested by the interior bending cohort. Pixel-row cap alignment bins do not show a simple monotonic increase toward row boundaries.','',
        'In the images, 85.72% of clipped squared error is on partially covered target pixels. The three-row bands centered on each cap row contribute 38.98%; these bands include one row before and after the pixel row containing each cap. Image locations and positions in the five-knob parameter box are distinct questions.','',
        'The strong-bending/small-error and weak-bending/large-error examples are deliberate counterexamples within the high/low bending deciles at scale 0.02; they are selected for small/large reconstruction errors, not representatives of average group errors.','',
        'Reproduce from the repository root: `.venv/bin/python analyze_generated_one_error_location.py`, then `.venv/bin/python make_generated_one_error_location_view.py`. Read `results.json` and the NPZ files for all numerical definitions, cohort indices and measured features.']
    (OUT/'README.md').write_text('\n'.join(lines)+'\n')


if __name__=='__main__':main()
